name: Build and Push Docker Image to Docker Hub

on:
  schedule:
    - cron: '0 0 * * 6'
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: pabuk/dev-python

jobs:
  build-and-test:
    if: github.repository == 'PAB-me-uk/dev-docker-image'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}:${{ matrix.PYTHON_VERSION }} --no-cache --force-rm --build-arg IMAGE_PYTHON_VERSION=${{ matrix.PYTHON_VERSION }}
      - name: Test the Docker image
        run: docker run --rm -t ${{ env.IMAGE_NAME }}:${{ matrix.PYTHON_VERSION }} bin/zsh -c "source ~/.zshrc && check-container"
      - name: Push the Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ matrix.PYTHON_VERSION }}
